# taskq default tmux config. Local ~/.tmux.conf is not loaded for tq.
set -g prefix None
unbind-key C-b
bind-key -n C-c detach-client
bind-key -T copy-mode C-c detach-client
bind-key -T copy-mode-vi C-c detach-client
bind-key -n C-b copy-mode -u
bind-key -n C-f copy-mode
bind-key -T copy-mode C-b send-keys -X page-up
bind-key -T copy-mode-vi C-b send-keys -X page-up
bind-key -T copy-mode C-f send-keys -X page-down
bind-key -T copy-mode-vi C-f send-keys -X page-down
set -g default-shell /bin/sh
set -g status off
set -g history-limit 100000
setw -g remain-on-exit off
setw -g allow-rename off
setw -g automatic-rename off
